CREATE TABLE RouletteWheel
(
	IdRouletteWheel NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	Estado SMALLINT DEFAULT(0)
)

CREATE TABLE RoundBet
(
	IdRoundBet NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	IdRouletteWheel NUMERIC (18,0) NOT NULL,
	RoundBetOpen BIT DEFAULT(1),
	DateOpened DATETIME NOT NULL DEFAULT(GETDATE()),
	DateClosed DATETIME,
	CONSTRAINT fk_RouletteWheel FOREIGN KEY (IdRouletteWheel) REFERENCES RouletteWheel (IdRouletteWheel)
)

CREATE TABLE Bets
(
	IdBet NUMERIC(18,0) IDENTITY PRIMARY KEY NOT NULL,
	IdRoundBet NUMERIC(18,0) NOT NULL,
	Username NVARCHAR(50) NOT NULL,
	TypeBet SMALLINT NOT NULL,
	SingleNumber SMALLINT,
	SingleColor NVARCHAR(10),
	Amount MONEY NOT NULL,
	CONSTRAINT fk_RoundBet FOREIGN KEY (IdRoundBet) REFERENCES RoundBet (IdRoundBet)
)

CREATE TABLE WinningBets
(
	IdRoundBet NUMERIC(18,0) PRIMARY KEY NOT NULL,
	WinningNumber SMALLINT NOT NULL,
	WinningColor NVARCHAR(10) NOT NULL,
	DateWinner DATETIME DEFAULT(GETDATE())
	CONSTRAINT fk_RoundBet_WinningBets FOREIGN KEY (IdRoundBet) REFERENCES RoundBet (IdRoundBet)
)

CREATE TABLE Prizes
(
	TypeBet INT PRIMARY KEY NOT NULL,
	BetPrize DECIMAL(10,2) NOT NULL
)

INSERT INTO Prizes VALUES (1, 5)
INSERT INTO Prizes VALUES (2, 1.8)